travis:
  secure:
    BINSTAR_TOKEN: Wo+FkzUz5xywnSgRZ9y57Exyuo1soBd52pZ1kyA01wG4qz2bD6ZjXx+BjM5Iggx2Rnir6iVNC3oR91NpS0dxkSXAU719q0a7YvwzcsflKE2Kgv2U+z5AIl5ciKyUJS+YQQDrje5AX6svmThmXTrgsPw8rSLgFX3nC3fJa4bDgbLkwgdmGV/eAvJfVuo3p5TUg+EnapU2XBF3ayutMmg8EUCbBMGlEdxao7jyz5iddWmKVj3fPPsXM6O99JQ3Ia2vpwMLowUDV+3yHzmS41r9tOODbSN3PTUmkI9CQTeSM8P0dJ3KXrIZle+5Vn2zC3Ju1FHykBBpz1W/WYeg5h1ditq2hJLXecmsOOZfNty225+64PisnzJEdLXPjPZqK3W2fCBh0aH7f6IQ0j2gyViynlUxMc+FWIJJNU5B4d4kmk0A6yuKXP4HrhFaTEk5SJZtOy3rThUCXPAjGmxZzh9hMV2rpkmVIQooMm91xoVnpmW0cAlzcm/wvqDG8TVzToyorp0JVguGi4gyeFL1axf3lGAm0kK2NPtpbnV+bd4Iat/sD1cBehHMwqonv80lg7nZyhaEAN4Cj7O9pA6CJahfZ8EnNwtULRlnSGBWxSOFwZ3+nXzsxX6rJ1WNfFvc9IjSYoxyw5JcCKptYs8h/RIgmd7diTjInJ4zJuxjUF7wuJw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
